name: 'Run private script'
description: 'Run private script and clean afterwards'

inputs:
  repo:
    description: 'What repo to run'
    required: true
  token:
    description: 'Github token'
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout private action
      uses: actions/checkout@v2
      with:
        submodules: true
        repository: ${{ inputs.repo }}
        token: ${{ inputs.token }}
        path: ./.private-actions

    - name: Post checkout
      run: echo "Actions available in ./.private-actions"
      shell: bash
